name: flutter_map_cancellable_tile_provider
description: Plugin for flutter_map that provides a `TileProvider` with the capability to cancel unnecessary HTTP requests
version: 1.0.0

homepage: https://github.com/fleaflet/flutter_map
repository: https://github.com/fleaflet/flutter_map_cancellable_tile_provider
issue_tracker: https://github.com/fleaflet/flutter_map/issues
documentation: https://docs.fleaflet.dev

topics:
  - flutter-map
  - map

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0-dev.3
