name: "Branch & Fork CI/CD"
on:
  push:
    branches:
      - '!master'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  score-package:
    name: "Score Package"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Dart Package Analyser
        uses: axel-op/dart-package-analyzer@master
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Package Scores
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          if (( $TOTAL < $TOTAL_MAX - 10 ))
          then
            echo Package score less than available score. Improve the score!
            exit 1
          fi
    
  analyse-code:
    name: "Analyse Code"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Get All Dependencies
        run: flutter pub get
      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Check Lints
        run: dart analyze --fatal-infos --fatal-warnings